CREATE TABLE Players
(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) UNIQUE,
    PRIMARY KEY (id)
);

CREATE TABLE Matches
(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    Player1 INT,
    Player2 INT,
    Winner INT,
    PRIMARY KEY (id),
    CONSTRAINT chk_matches_players_not_equal CHECK (Player1 <> Player2),
    CONSTRAINT chk_matches_valid_winner CHECK (Winner = Player1 OR Winner = Player2),
    CONSTRAINT FK_matches_player1 FOREIGN KEY (Player1) REFERENCES Players (id),
    CONSTRAINT FK_matches_player2 FOREIGN KEY (Player2) REFERENCES Players (id),
    CONSTRAINT FK_matches_winner FOREIGN KEY (Winner) REFERENCES Players (id)
);